// Note: Keys match the names defined in lib/countries.ts where possible.
// We normalize certain variations and include common alternates.

function norm(s: string) {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9 ]/g, "")
    .replace(/\s+/g, " ")
    .trim()
}

// Core mapping for African countries + many common world countries.
// Unknown entries return undefined so callers can gracefully skip the flag.
const MAP: Record<string, string> = {
  // Africa
  algeria: "DZ",
  angola: "AO",
  benin: "BJ",
  botswana: "BW",
  "burkina faso": "BF",
  burundi: "BI",
  "cabo verde": "CV",
  "cape verde": "CV",
  cameroon: "CM",
  "central african republic": "CF",
  chad: "TD",
  comoros: "KM",
  congo: "CG", // Republic of the Congo
  "democratic republic of the congo": "CD",
  djibouti: "DJ",
  egypt: "EG",
  "equatorial guinea": "GQ",
  eritrea: "ER",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  gabon: "GA",
  gambia: "GM",
  ghana: "GH",
  guinea: "GN",
  guineabissau: "GW",
  "ivory coast": "CI",
  "cote divoire": "CI",
  kenya: "KE",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  madagascar: "MG",
  malawi: "MW",
  mali: "ML",
  mauritania: "MR",
  mauritius: "MU",
  morocco: "MA",
  mozambique: "MZ",
  namibia: "NA",
  niger: "NE",
  nigeria: "NG",
  rwanda: "RW",
  "sao tome and principe": "ST",
  "são tome and príncipe": "ST",
  senegal: "SN",
  seychelles: "SC",
  "sierra leone": "SL",
  somalia: "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  sudan: "SD",
  tanzania: "TZ",
  togo: "TG",
  tunisia: "TN",
  uganda: "UG",
  zambia: "ZM",
  zimbabwe: "ZW",
  "african diaspora": "", // no specific flag; returning empty to skip

  // Common production locations worldwide (and the rest of WORLD_COUNTRIES frequently used)
  afghanistan: "AF",
  albania: "AL",
  andorra: "AD",
  "antigua and barbuda": "AG",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  bahrain: "BH",
  bangladesh: "BD",
  barbados: "BB",
  belarus: "BY",
  belgium: "BE",
  belize: "BZ",
  bhutan: "BT",
  bolivia: "BO",
  "bosnia and herzegovina": "BA",
  brazil: "BR",
  brunei: "BN",
  bulgaria: "BG",
  cambodia: "KH",
  canada: "CA",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  dominica: "DM",
  "dominican republic": "DO",
  ecuador: "EC",
  "el salvador": "SV",
  estonia: "EE",
  fiji: "FJ",
  finland: "FI",
  france: "FR",
  georgia: "GE",
  germany: "DE",
  greece: "GR",
  grenada: "GD",
  guatemala: "GT",
  guyana: "GY",
  haiti: "HT",
  honduras: "HN",
  "hong kong": "HK",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kiribati: "KI",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  latvia: "LV",
  lebanon: "LB",
  liechtenstein: "LI",
  lithuania: "LT",
  luxembourg: "LU",
  malaysia: "MY",
  maldives: "MV",
  malta: "MT",
  "marshall islands": "MH",
  mexico: "MX",
  micronesia: "FM",
  moldova: "MD",
  monaco: "MC",
  mongolia: "MN",
  montenegro: "ME",
  myanmar: "MM",
  nauru: "NR",
  nepal: "NP",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NI",
  "north korea": "KP",
  "north macedonia": "MK",
  norway: "NO",
  oman: "OM",
  pakistan: "PK",
  palau: "PW",
  palestine: "PS",
  panama: "PA",
  "papua new guinea": "PG",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  "saudi arabia": "SA",
  serbia: "RS",
  singapore: "SG",
  slovakia: "SK",
  slovenia: "SI",
  "solomon islands": "SB",
  "south korea": "KR",
  spain: "ES",
  "sri lanka": "LK",
  suriname: "SR",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  taiwan: "TW",
  tajikistan: "TJ",
  thailand: "TH",
  timorleste: "TL",
  tonga: "TO",
  "trinidad and tobago": "TT",
  turkey: "TR",
  turkmenistan: "TM",
  tuvalu: "TV",
  ukraine: "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  "united states of america": "US",
  usa: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  vanuatu: "VU",
  "vatican city": "VA",
  venezuela: "VE",
  vietnam: "VN",
  yemen: "YE",
  vatican: "VA",
}

// Special aliases to Congo variants
// 'congo' already maps to CG, DRC maps to CD via the long name above.

export function countryNameToIso2(name: string): string | undefined {
  const n = norm(name)
  const code = MAP[n]
  // empty string used to explicitly skip flags (e.g., African Diaspora)
  if (code === "") {
    console.log("MISSING COUNTRY: ", name)
    return undefined
  }
  return code
}
