export const LANGUAGES = [
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Chewa (Nyanja)",
  "Chibarwe",
  "Comorian",
  "English",
  "French",
  "Hausa",
  "Igbo",
  "Kalanga",
  "Kinyarwanda",
  "Kirundi",
  "Koisan",
  "Nambya",
  "Ndau",
  "Ndebele",
  "Northern Sotho (Sepedi)",
  "Oromo",
  "Portuguese",
  "Sango",
  "Sesotho (Southern Sotho)",
  "Seychellois Creole",
  "Shangani",
  "Shona",
  "sign language",
  "Somali",
  "Spanish",
  "Swahili",
  "Swati (siSwati)",
  "Tamazight (Berber)",
  "Tigrinya",
  "Tsonga",
  "Tswana (Setswana)",
  "Venda",
  "Wolof",
  "Xhosa",
  "Yoruba",
  "Zulu",
]
