-- Insert sample designers
INSERT INTO public.designers (name, bio, location, website_url, instagram_url, specialties, years_experience, price_range, sustainability_rating, featured, status) VALUES
('Amara Okafor', 'Sustainable fashion designer specializing in African-inspired contemporary wear. Committed to ethical production and supporting local artisans.', 'Lagos, Nigeria', 'https://amaraokafor.com', 'https://instagram.com/amaraokafor', ARRAY['Fashion', 'Sustainable', 'Contemporary'], 8, '$$$', 5, true, 'active'),
('Kofi Asante', 'Luxury menswear designer known for innovative tailoring and modern African aesthetics. Featured in Vogue and GQ.', 'Accra, Ghana', 'https://kofiasante.com', 'https://instagram.com/kofiasante', ARRAY['Menswear', 'Luxury', 'Tailoring'], 12, '$$$$', 4, true, 'active'),
('Zara Mbeki', 'Accessories designer creating handcrafted jewelry and bags using traditional techniques with contemporary design.', 'Cape Town, South Africa', 'https://zarambeki.co.za', 'https://instagram.com/zarambeki', ARRAY['Accessories', 'Jewelry', 'Handcrafted'], 6, '$$', 5, false, 'active'),
('Fatima Al-Rashid', 'Modest fashion designer blending Middle Eastern heritage with modern silhouettes for the contemporary woman.', 'Dubai, UAE', 'https://fatimaalrashid.com', 'https://instagram.com/fatimaalrashid', ARRAY['Modest Fashion', 'Contemporary', 'Womenswear'], 10, '$$$', 3, true, 'active');

-- Insert sample blog posts
INSERT INTO public.blog_posts (title, slug, excerpt, content, author_name, author_bio, tags, featured, published, published_at) VALUES
('The Rise of Sustainable Fashion in Africa', 'rise-of-sustainable-fashion-africa', 'Exploring how African designers are leading the global sustainable fashion movement with innovative approaches to eco-friendly design.', 'African fashion designers are at the forefront of the sustainable fashion revolution, combining traditional techniques with modern innovation to create environmentally conscious designs that honor cultural heritage while addressing contemporary needs...', 'Sarah Johnson', 'Fashion journalist and sustainability advocate with 10 years of experience covering African fashion.', ARRAY['Sustainability', 'African Fashion', 'Innovation'], true, true, NOW() - INTERVAL '2 days'),
('Spotlight: Emerging Designers to Watch', 'emerging-designers-spotlight', 'Meet the next generation of fashion innovators who are reshaping the industry with fresh perspectives and bold creativity.', 'The fashion industry is constantly evolving, driven by emerging talents who bring fresh perspectives and innovative approaches to design. In this spotlight, we feature five rising stars who are making waves in the fashion world...', 'Marcus Chen', 'Fashion editor and trend forecaster specializing in emerging talent discovery.', ARRAY['Emerging Designers', 'Fashion Week', 'Innovation'], false, true, NOW() - INTERVAL '5 days'),
('The Art of Ethical Production', 'art-of-ethical-production', 'Understanding the importance of ethical manufacturing processes and how designers are creating positive change in the industry.', 'Ethical production has become more than just a buzzword in the fashion industry. It represents a fundamental shift towards responsible manufacturing that prioritizes worker welfare, environmental protection, and sustainable practices...', 'Dr. Aisha Patel', 'Sustainable fashion researcher and consultant with expertise in ethical supply chains.', ARRAY['Ethics', 'Production', 'Sustainability'], true, true, NOW() - INTERVAL '1 week');

-- Insert sample events
INSERT INTO public.events (title, slug, description, short_description, event_date, location, venue_name, ticket_url, price_info, organizer_name, tags, featured, published) VALUES
('African Fashion Week Lagos 2024', 'african-fashion-week-lagos-2024', 'The premier fashion event showcasing the best of African design talent. Join us for runway shows, designer exhibitions, and networking opportunities with industry leaders.', 'Premier African fashion showcase with runway shows and exhibitions.', NOW() + INTERVAL '2 months', 'Lagos, Nigeria', 'Eko Convention Centre', 'https://tickets.afw-lagos.com', 'From ₦15,000', 'African Fashion Week Organization', ARRAY['Fashion Week', 'Runway', 'Networking'], true, true),
('Sustainable Fashion Summit', 'sustainable-fashion-summit', 'A comprehensive conference focusing on sustainable practices in fashion design, production, and retail. Features keynote speakers, panel discussions, and workshops.', 'Conference on sustainable fashion practices and innovation.', NOW() + INTERVAL '6 weeks', 'Cape Town, South Africa', 'Cape Town International Convention Centre', 'https://sustainablefashionsummit.com/tickets', 'R850 - R2,500', 'Green Fashion Initiative', ARRAY['Sustainability', 'Conference', 'Workshop'], true, true),
('Designer Networking Mixer', 'designer-networking-mixer', 'An intimate networking event for fashion designers, buyers, and industry professionals. Connect with peers, share ideas, and explore collaboration opportunities.', 'Intimate networking event for fashion professionals.', NOW() + INTERVAL '3 weeks', 'Accra, Ghana', 'Kempinski Hotel Gold Coast City', 'https://eventbrite.com/designer-mixer', 'GH₵120', 'Ghana Fashion Collective', ARRAY['Networking', 'Collaboration'], false, true);
